from scenarios.reverberate.analyze_reverberate.aggregation_reverb import aggregation_reverb
from scenarios.reverberate.analyze_reverberate.fast_multi_minutes_reverb import fast_multi_minutes_reverb
from scenarios.reverberate.analyze_reverberate.fast_reverb import fast_reverb
from scenarios.reverberate.analyze_reverberate.plot_reverb import plot_reverb

from scenarios.reverberate.history_reverberate.history_reverberate import history_reverberate
from scenarios.reverberate.selenium_reverberate.selenium_reverberate import selenium_reverberate



def reverberate():
    fast_multi_minutes_reverb('files/reverberation_data_BTCUSDT_binance.json')
